name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - scala: 2.12.13
          - scala: 2.13.4
          - scala: 3.0.0-RC1
          - scala: 3.0.0-RC2-bin-20210219-aa7c21e-NIGHTLY
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - uses: coursier/cache-action@v5
    - run: sbt -v "++ ${{matrix.scala}}!" compile
